logging:
  config: /config/logback-spring.xml
server:
  port: ${port:8080}
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ads?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
application:
  delivery:
    rest:
      url: http://192.168.0.133:9083/sendMultipleMessages
  shortenerUrl:
    rest:
      url: http://192.168.0.133:9084/receive
  billingAdmin:
    url: http://localhost:5008
    smsi:
      processPackage: /transaction